name: Compile with SourceMod

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        sm_version: ['1.7', '1.8', '1.9', '1.10', '1.11']

    steps:
      - uses: actions/checkout@v1

      - name: Setup Environment
        run: |
          SOURCEMOD_PATH=$GITHUB_WORKSPACE/addons/sourcemod
          echo ::set-env name=SOURCEMOD_PATH::$SOURCEMOD_PATH
          echo ::set-env name=SCRIPTS_PATH::$SOURCEMOD_PATH/scripting
          echo ::set-env name=INCLUDE_PATH::$SCRIPTS_PATH/include

      - name: Setup SourcePawn Compiler ${{ matrix.sm_version }}
        uses: rumblefrog/setup-sp@master
        with:
          version: ${{ matrix.sm_version }}

      - name: Compile Plugin
        run: spcomp -i$INCLUDE_PATH $SCRIPTS_PATH/json_test.sp
